# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI-LIBTwinSVM.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 354)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 641, 311))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 151, 81))
        self.groupBox.setObjectName("groupBox")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(10, 20, 111, 17))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 50, 141, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 190, 411, 81))
        self.groupBox_5.setObjectName("groupBox_5")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar.setGeometry(QtCore.QRect(10, 50, 401, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(110, 20, 47, 21))
        self.label_9.setObjectName("label_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(160, 10, 120, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 20, 82, 17))
        self.radioButton_3.setChecked(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 40, 82, 17))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 60, 82, 17))
        self.radioButton_5.setObjectName("radioButton_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(290, 10, 121, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 20, 101, 17))
        self.radioButton_6.setObjectName("radioButton_6")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setGeometry(QtCore.QRect(10, 40, 31, 16))
        self.label.setObjectName("label")
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setGeometry(QtCore.QRect(40, 40, 42, 22))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10)
        self.spinBox.setProperty("value", 5)
        self.spinBox.setObjectName("spinBox")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox_3)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 70, 91, 17))
        self.radioButton_7.setObjectName("radioButton_7")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 61, 16))
        self.label_2.setObjectName("label_2")
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_2.setGeometry(QtCore.QRect(70, 90, 42, 22))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(99)
        self.spinBox_2.setProperty("value", 70)
        self.spinBox_2.setObjectName("spinBox_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 100, 281, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 21, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox_3 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_3.setGeometry(QtCore.QRect(30, 20, 42, 22))
        self.spinBox_3.setMinimum(-10)
        self.spinBox_3.setMaximum(0)
        self.spinBox_3.setProperty("value", -5)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(80, 20, 16, 16))
        self.label_4.setObjectName("label_4")
        self.spinBox_4 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_4.setGeometry(QtCore.QRect(100, 20, 42, 22))
        self.spinBox_4.setMinimum(1)
        self.spinBox_4.setMaximum(10)
        self.spinBox_4.setProperty("value", 5)
        self.spinBox_4.setObjectName("spinBox_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(150, 20, 21, 16))
        self.label_5.setObjectName("label_5")
        self.spinBox_5 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_5.setGeometry(QtCore.QRect(170, 20, 42, 22))
        self.spinBox_5.setMinimum(-10)
        self.spinBox_5.setMaximum(0)
        self.spinBox_5.setProperty("value", -5)
        self.spinBox_5.setObjectName("spinBox_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(220, 20, 16, 16))
        self.label_6.setObjectName("label_6")
        self.spinBox_6 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_6.setGeometry(QtCore.QRect(240, 20, 42, 22))
        self.spinBox_6.setMinimum(1)
        self.spinBox_6.setMaximum(10)
        self.spinBox_6.setProperty("value", 5)
        self.spinBox_6.setObjectName("spinBox_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 21, 16))
        self.label_7.setObjectName("label_7")
        self.spinBox_7 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_7.setGeometry(QtCore.QRect(30, 50, 42, 22))
        self.spinBox_7.setMinimum(-20)
        self.spinBox_7.setMaximum(0)
        self.spinBox_7.setProperty("value", -5)
        self.spinBox_7.setObjectName("spinBox_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setGeometry(QtCore.QRect(80, 50, 16, 16))
        self.label_8.setObjectName("label_8")
        self.spinBox_8 = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_8.setGeometry(QtCore.QRect(100, 50, 42, 22))
        self.spinBox_8.setMinimum(1)
        self.spinBox_8.setMaximum(10)
        self.spinBox_8.setProperty("value", 5)
        self.spinBox_8.setObjectName("spinBox_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Classifiers"))
        self.radioButton.setText(_translate("MainWindow", "Standard TwinSVM"))
        self.radioButton_2.setText(_translate("MainWindow", "Least Squares TwinSVM"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Grid Search"))
        self.pushButton.setText(_translate("MainWindow", "Run!"))
        self.label_9.setText(_translate("MainWindow", "Best Acc:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Kernel"))
        self.radioButton_3.setText(_translate("MainWindow", "Linear"))
        self.radioButton_4.setText(_translate("MainWindow", "RBF"))
        self.radioButton_5.setText(_translate("MainWindow", "Rectangular"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Evaluation"))
        self.radioButton_6.setText(_translate("MainWindow", "Cross-validation"))
        self.label.setText(_translate("MainWindow", "Folds:"))
        self.radioButton_7.setText(_translate("MainWindow", "Train/Test split"))
        self.label_2.setText(_translate("MainWindow", "Percentage:"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Hyper-Parameters"))
        self.label_3.setText(_translate("MainWindow", "C1:"))
        self.label_4.setText(_translate("MainWindow", "to"))
        self.label_5.setText(_translate("MainWindow", "C2:"))
        self.label_6.setText(_translate("MainWindow", "to"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>u:</p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "to"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
