# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\GUI-LIBTwinSVM.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
# icons_rc should be imported as follows
from . import icons_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(990, 708)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.main_win = QtWidgets.QWidget(MainWindow)
        self.main_win.setObjectName("main_win")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_win)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabs = QtWidgets.QTabWidget(self.main_win)
        self.tabs.setEnabled(True)
        self.tabs.setObjectName("tabs")
        self.data_tab = QtWidgets.QWidget()
        self.data_tab.setObjectName("data_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.data_tab)
        self.gridLayout.setObjectName("gridLayout")
        self.data_tab_frame = QtWidgets.QFrame(self.data_tab)
        self.data_tab_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_tab_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.data_tab_frame.setObjectName("data_tab_frame")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.data_tab_frame)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.feature_box = QtWidgets.QGroupBox(self.data_tab_frame)
        self.feature_box.setObjectName("feature_box")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.feature_box)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.feature_table = QtWidgets.QTableWidget(self.feature_box)
        self.feature_table.setMinimumSize(QtCore.QSize(72, 200))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.feature_table.setFont(font)
        self.feature_table.setColumnCount(1)
        self.feature_table.setObjectName("feature_table")
        self.feature_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.feature_table.setHorizontalHeaderItem(0, item)
        self.gridLayout_13.addWidget(self.feature_table, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.feature_box, 4, 0, 1, 1)
        self.import_box = QtWidgets.QGroupBox(self.data_tab_frame)
        self.import_box.setObjectName("import_box")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.import_box)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.header_ha_lay = QtWidgets.QHBoxLayout()
        self.header_ha_lay.setObjectName("header_ha_lay")
        self.header_check = QtWidgets.QCheckBox(self.import_box)
        self.header_check.setChecked(True)
        self.header_check.setObjectName("header_check")
        self.header_ha_lay.addWidget(self.header_check)
        self.sep_label = QtWidgets.QLabel(self.import_box)
        self.sep_label.setObjectName("sep_label")
        self.header_ha_lay.addWidget(self.sep_label)
        self.sep_char_box = QtWidgets.QLineEdit(self.import_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sep_char_box.sizePolicy().hasHeightForWidth())
        self.sep_char_box.setSizePolicy(sizePolicy)
        self.sep_char_box.setMaximumSize(QtCore.QSize(32, 16777215))
        self.sep_char_box.setMaxLength(1)
        self.sep_char_box.setObjectName("sep_char_box")
        self.header_ha_lay.addWidget(self.sep_char_box)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_ha_lay.addItem(spacerItem1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.header_ha_lay.addItem(spacerItem2)
        self.gridLayout_11.addLayout(self.header_ha_lay, 1, 0, 1, 1)
        self.path_hz_lay = QtWidgets.QHBoxLayout()
        self.path_hz_lay.setObjectName("path_hz_lay")
        self.path_label = QtWidgets.QLabel(self.import_box)
        self.path_label.setObjectName("path_label")
        self.path_hz_lay.addWidget(self.path_label)
        self.path_box = QtWidgets.QLineEdit(self.import_box)
        self.path_box.setObjectName("path_box")
        self.path_hz_lay.addWidget(self.path_box)
        self.open_btn = QtWidgets.QPushButton(self.import_box)
        self.open_btn.setObjectName("open_btn")
        self.path_hz_lay.addWidget(self.open_btn)
        self.gridLayout_11.addLayout(self.path_hz_lay, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.import_box, 0, 0, 1, 2)
        self.info_box = QtWidgets.QGroupBox(self.data_tab_frame)
        self.info_box.setObjectName("info_box")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.info_box)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.feature_label = QtWidgets.QLabel(self.info_box)
        self.feature_label.setObjectName("feature_label")
        self.gridLayout_12.addWidget(self.feature_label, 0, 2, 1, 1)
        self.no_features = QtWidgets.QLabel(self.info_box)
        self.no_features.setObjectName("no_features")
        self.gridLayout_12.addWidget(self.no_features, 0, 3, 1, 1)
        self.class_label = QtWidgets.QLabel(self.info_box)
        self.class_label.setObjectName("class_label")
        self.gridLayout_12.addWidget(self.class_label, 0, 4, 1, 1)
        self.no_classes = QtWidgets.QLabel(self.info_box)
        self.no_classes.setObjectName("no_classes")
        self.gridLayout_12.addWidget(self.no_classes, 0, 5, 1, 1)
        self.samples_label = QtWidgets.QLabel(self.info_box)
        self.samples_label.setObjectName("samples_label")
        self.gridLayout_12.addWidget(self.samples_label, 0, 0, 1, 1)
        self.no_samples = QtWidgets.QLabel(self.info_box)
        self.no_samples.setObjectName("no_samples")
        self.gridLayout_12.addWidget(self.no_samples, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.info_box, 3, 0, 1, 2)
        self.read_box = QtWidgets.QGroupBox(self.data_tab_frame)
        self.read_box.setEnabled(False)
        self.read_box.setObjectName("read_box")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.read_box)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.read_hz_lay = QtWidgets.QHBoxLayout()
        self.read_hz_lay.setObjectName("read_hz_lay")
        self.normalize_box = QtWidgets.QCheckBox(self.read_box)
        self.normalize_box.setEnabled(False)
        self.normalize_box.setObjectName("normalize_box")
        self.read_hz_lay.addWidget(self.normalize_box)
        self.shuffle_box = QtWidgets.QCheckBox(self.read_box)
        self.shuffle_box.setEnabled(False)
        self.shuffle_box.setObjectName("shuffle_box")
        self.read_hz_lay.addWidget(self.shuffle_box)
        self.gridLayout_14.addLayout(self.read_hz_lay, 0, 0, 1, 1)
        self.load_btn = QtWidgets.QPushButton(self.read_box)
        self.load_btn.setEnabled(False)
        self.load_btn.setObjectName("load_btn")
        self.gridLayout_14.addWidget(self.load_btn, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_10.addWidget(self.read_box, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.data_tab_frame, 0, 0, 1, 1)
        self.tabs.addTab(self.data_tab, "")
        self.classify_tab = QtWidgets.QWidget()
        self.classify_tab.setEnabled(True)
        self.classify_tab.setObjectName("classify_tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.classify_tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.classigy_tab_frame = QtWidgets.QFrame(self.classify_tab)
        self.classigy_tab_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.classigy_tab_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.classigy_tab_frame.setObjectName("classigy_tab_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.classigy_tab_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.classifiers_box = QtWidgets.QGroupBox(self.classigy_tab_frame)
        self.classifiers_box.setObjectName("classifiers_box")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.classifiers_box)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.STSVM_rbtn = QtWidgets.QRadioButton(self.classifiers_box)
        self.STSVM_rbtn.setChecked(True)
        self.STSVM_rbtn.setObjectName("STSVM_rbtn")
        self.gridLayout_2.addWidget(self.STSVM_rbtn, 0, 0, 1, 1)
        self.LSTSVM_rbtn = QtWidgets.QRadioButton(self.classifiers_box)
        self.LSTSVM_rbtn.setObjectName("LSTSVM_rbtn")
        self.gridLayout_2.addWidget(self.LSTSVM_rbtn, 1, 0, 1, 1)
        self.mc_box = QtWidgets.QGroupBox(self.classifiers_box)
        self.mc_box.setEnabled(True)
        self.mc_box.setObjectName("mc_box")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.mc_box)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.mc_hz_lay = QtWidgets.QHBoxLayout()
        self.mc_hz_lay.setObjectName("mc_hz_lay")
        self.ova_rbtn = QtWidgets.QRadioButton(self.mc_box)
        self.ova_rbtn.setEnabled(False)
        self.ova_rbtn.setChecked(True)
        self.ova_rbtn.setObjectName("ova_rbtn")
        self.mc_hz_lay.addWidget(self.ova_rbtn)
        self.ovo_rbtn = QtWidgets.QRadioButton(self.mc_box)
        self.ovo_rbtn.setEnabled(False)
        self.ovo_rbtn.setObjectName("ovo_rbtn")
        self.mc_hz_lay.addWidget(self.ovo_rbtn)
        self.gridLayout_16.addLayout(self.mc_hz_lay, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.mc_box, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.classifiers_box, 0, 0, 1, 1)
        self.eval_box = QtWidgets.QGroupBox(self.classigy_tab_frame)
        self.eval_box.setObjectName("eval_box")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.eval_box)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cv_rbtn = QtWidgets.QRadioButton(self.eval_box)
        self.cv_rbtn.setChecked(True)
        self.cv_rbtn.setObjectName("cv_rbtn")
        self.gridLayout_6.addWidget(self.cv_rbtn, 0, 0, 1, 1)
        self.tt_split_rbtn = QtWidgets.QRadioButton(self.eval_box)
        self.tt_split_rbtn.setObjectName("tt_split_rbtn")
        self.gridLayout_6.addWidget(self.tt_split_rbtn, 2, 0, 1, 1)
        self.fold_hz_lay = QtWidgets.QHBoxLayout()
        self.fold_hz_lay.setObjectName("fold_hz_lay")
        self.folds_label = QtWidgets.QLabel(self.eval_box)
        self.folds_label.setObjectName("folds_label")
        self.fold_hz_lay.addWidget(self.folds_label)
        self.cv_folds = QtWidgets.QSpinBox(self.eval_box)
        self.cv_folds.setMinimum(1)
        self.cv_folds.setMaximum(10)
        self.cv_folds.setProperty("value", 5)
        self.cv_folds.setObjectName("cv_folds")
        self.fold_hz_lay.addWidget(self.cv_folds)
        self.gridLayout_6.addLayout(self.fold_hz_lay, 1, 0, 1, 1)
        self.tt_percent_hz_lay = QtWidgets.QHBoxLayout()
        self.tt_percent_hz_lay.setObjectName("tt_percent_hz_lay")
        self.tt_percent_label = QtWidgets.QLabel(self.eval_box)
        self.tt_percent_label.setObjectName("tt_percent_label")
        self.tt_percent_hz_lay.addWidget(self.tt_percent_label)
        self.tt_percentage = QtWidgets.QSpinBox(self.eval_box)
        self.tt_percentage.setEnabled(False)
        self.tt_percentage.setMinimum(1)
        self.tt_percentage.setMaximum(99)
        self.tt_percentage.setProperty("value", 70)
        self.tt_percentage.setObjectName("tt_percentage")
        self.tt_percent_hz_lay.addWidget(self.tt_percentage)
        self.gridLayout_6.addLayout(self.tt_percent_hz_lay, 3, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem4, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.eval_box, 0, 2, 1, 1)
        self.kernel_box = QtWidgets.QGroupBox(self.classigy_tab_frame)
        self.kernel_box.setObjectName("kernel_box")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.kernel_box)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lin_kernel_rbtn = QtWidgets.QRadioButton(self.kernel_box)
        self.lin_kernel_rbtn.setChecked(True)
        self.lin_kernel_rbtn.setObjectName("lin_kernel_rbtn")
        self.gridLayout_7.addWidget(self.lin_kernel_rbtn, 0, 0, 1, 1)
        self.rbf_kernel_rbtn = QtWidgets.QRadioButton(self.kernel_box)
        self.rbf_kernel_rbtn.setObjectName("rbf_kernel_rbtn")
        self.gridLayout_7.addWidget(self.rbf_kernel_rbtn, 1, 0, 1, 1)
        self.rect_kernel_rbtn = QtWidgets.QRadioButton(self.kernel_box)
        self.rect_kernel_rbtn.setObjectName("rect_kernel_rbtn")
        self.gridLayout_7.addWidget(self.rect_kernel_rbtn, 2, 0, 1, 1)
        self.rect_hz_lay = QtWidgets.QHBoxLayout()
        self.rect_hz_lay.setObjectName("rect_hz_lay")
        self.percent_label = QtWidgets.QLabel(self.kernel_box)
        self.percent_label.setObjectName("percent_label")
        self.rect_hz_lay.addWidget(self.percent_label)
        self.rect_kernel_percent = QtWidgets.QSpinBox(self.kernel_box)
        self.rect_kernel_percent.setEnabled(False)
        self.rect_kernel_percent.setMinimum(5)
        self.rect_kernel_percent.setProperty("value", 75)
        self.rect_kernel_percent.setObjectName("rect_kernel_percent")
        self.rect_hz_lay.addWidget(self.rect_kernel_percent)
        self.gridLayout_7.addLayout(self.rect_hz_lay, 3, 0, 1, 1)
        self.gridLayout_5.addWidget(self.kernel_box, 0, 1, 1, 1)
        self.hparam_box = QtWidgets.QGroupBox(self.classigy_tab_frame)
        self.hparam_box.setObjectName("hparam_box")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.hparam_box)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.c2_hz_lay = QtWidgets.QHBoxLayout()
        self.c2_hz_lay.setObjectName("c2_hz_lay")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.c2_hz_lay.addItem(spacerItem5)
        self.C2_label = QtWidgets.QLabel(self.hparam_box)
        self.C2_label.setObjectName("C2_label")
        self.c2_hz_lay.addWidget(self.C2_label)
        self.C2_lbound = QtWidgets.QSpinBox(self.hparam_box)
        self.C2_lbound.setMinimum(-10)
        self.C2_lbound.setMaximum(0)
        self.C2_lbound.setProperty("value", -5)
        self.C2_lbound.setObjectName("C2_lbound")
        self.c2_hz_lay.addWidget(self.C2_lbound)
        self.c2_to_label = QtWidgets.QLabel(self.hparam_box)
        self.c2_to_label.setObjectName("c2_to_label")
        self.c2_hz_lay.addWidget(self.c2_to_label)
        self.C2_ubound = QtWidgets.QSpinBox(self.hparam_box)
        self.C2_ubound.setMinimum(1)
        self.C2_ubound.setMaximum(10)
        self.C2_ubound.setProperty("value", 5)
        self.C2_ubound.setObjectName("C2_ubound")
        self.c2_hz_lay.addWidget(self.C2_ubound)
        self.gridLayout_8.addLayout(self.c2_hz_lay, 0, 1, 1, 1)
        self.c1_hz_lay = QtWidgets.QHBoxLayout()
        self.c1_hz_lay.setObjectName("c1_hz_lay")
        self.C1_label = QtWidgets.QLabel(self.hparam_box)
        self.C1_label.setObjectName("C1_label")
        self.c1_hz_lay.addWidget(self.C1_label)
        self.C1_lbound = QtWidgets.QSpinBox(self.hparam_box)
        self.C1_lbound.setMinimum(-10)
        self.C1_lbound.setMaximum(0)
        self.C1_lbound.setProperty("value", -5)
        self.C1_lbound.setObjectName("C1_lbound")
        self.c1_hz_lay.addWidget(self.C1_lbound)
        self.c1_to_label = QtWidgets.QLabel(self.hparam_box)
        self.c1_to_label.setObjectName("c1_to_label")
        self.c1_hz_lay.addWidget(self.c1_to_label)
        self.C1_ubound = QtWidgets.QSpinBox(self.hparam_box)
        self.C1_ubound.setMinimum(1)
        self.C1_ubound.setMaximum(10)
        self.C1_ubound.setProperty("value", 5)
        self.C1_ubound.setObjectName("C1_ubound")
        self.c1_hz_lay.addWidget(self.C1_ubound)
        self.gridLayout_8.addLayout(self.c1_hz_lay, 0, 0, 1, 1)
        self.u_hz_lay = QtWidgets.QHBoxLayout()
        self.u_hz_lay.setObjectName("u_hz_lay")
        self.u_label = QtWidgets.QLabel(self.hparam_box)
        self.u_label.setObjectName("u_label")
        self.u_hz_lay.addWidget(self.u_label)
        self.u_lbound = QtWidgets.QSpinBox(self.hparam_box)
        self.u_lbound.setEnabled(False)
        self.u_lbound.setMinimum(-20)
        self.u_lbound.setMaximum(0)
        self.u_lbound.setProperty("value", -5)
        self.u_lbound.setObjectName("u_lbound")
        self.u_hz_lay.addWidget(self.u_lbound)
        self.u_to_label = QtWidgets.QLabel(self.hparam_box)
        self.u_to_label.setObjectName("u_to_label")
        self.u_hz_lay.addWidget(self.u_to_label)
        self.u_ubound = QtWidgets.QSpinBox(self.hparam_box)
        self.u_ubound.setEnabled(False)
        self.u_ubound.setMinimum(1)
        self.u_ubound.setMaximum(10)
        self.u_ubound.setProperty("value", 5)
        self.u_ubound.setObjectName("u_ubound")
        self.u_hz_lay.addWidget(self.u_ubound)
        self.gridLayout_8.addLayout(self.u_hz_lay, 1, 0, 1, 1)
        self.step_hz_lay = QtWidgets.QHBoxLayout()
        self.step_hz_lay.setObjectName("step_hz_lay")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.step_hz_lay.addItem(spacerItem6)
        self.step_label = QtWidgets.QLabel(self.hparam_box)
        self.step_label.setObjectName("step_label")
        self.step_hz_lay.addWidget(self.step_label)
        self.step_box_val = QtWidgets.QDoubleSpinBox(self.hparam_box)
        self.step_box_val.setMinimum(0.01)
        self.step_box_val.setMaximum(10.0)
        self.step_box_val.setSingleStep(0.25)
        self.step_box_val.setProperty("value", 1.0)
        self.step_box_val.setObjectName("step_box_val")
        self.step_hz_lay.addWidget(self.step_box_val)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.step_hz_lay.addItem(spacerItem7)
        self.gridLayout_8.addLayout(self.step_hz_lay, 1, 1, 1, 1)
        self.gridLayout_5.addWidget(self.hparam_box, 1, 0, 1, 1)
        self.gs_box = QtWidgets.QGroupBox(self.classigy_tab_frame)
        self.gs_box.setObjectName("gs_box")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gs_box)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.elapsed_time = QtWidgets.QLabel(self.gs_box)
        self.elapsed_time.setObjectName("elapsed_time")
        self.gridLayout_9.addWidget(self.elapsed_time, 0, 6, 1, 1)
        self.acc = QtWidgets.QLabel(self.gs_box)
        self.acc.setObjectName("acc")
        self.gridLayout_9.addWidget(self.acc, 0, 4, 1, 1)
        self.run_btn = QtWidgets.QPushButton(self.gs_box)
        self.run_btn.setEnabled(False)
        self.run_btn.setObjectName("run_btn")
        self.gridLayout_9.addWidget(self.run_btn, 0, 0, 1, 1)
        self.acc_label = QtWidgets.QLabel(self.gs_box)
        self.acc_label.setObjectName("acc_label")
        self.gridLayout_9.addWidget(self.acc_label, 0, 3, 1, 1)
        self.gs_progress_bar = QtWidgets.QProgressBar(self.gs_box)
        self.gs_progress_bar.setProperty("value", 0)
        self.gs_progress_bar.setObjectName("gs_progress_bar")
        self.gridLayout_9.addWidget(self.gs_progress_bar, 1, 0, 1, 6)
        self.best_acc_label = QtWidgets.QLabel(self.gs_box)
        self.best_acc_label.setObjectName("best_acc_label")
        self.gridLayout_9.addWidget(self.best_acc_label, 0, 1, 1, 1)
        self.elapsed_t_label = QtWidgets.QLabel(self.gs_box)
        self.elapsed_t_label.setObjectName("elapsed_t_label")
        self.gridLayout_9.addWidget(self.elapsed_t_label, 0, 5, 1, 1)
        self.best_acc = QtWidgets.QLabel(self.gs_box)
        self.best_acc.setObjectName("best_acc")
        self.gridLayout_9.addWidget(self.best_acc, 0, 2, 1, 1)
        self.gridLayout_5.addWidget(self.gs_box, 2, 0, 1, 3)
        self.save_res_gbox = QtWidgets.QGroupBox(self.classigy_tab_frame)
        self.save_res_gbox.setObjectName("save_res_gbox")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.save_res_gbox)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.clf_results_chk = QtWidgets.QCheckBox(self.save_res_gbox)
        self.clf_results_chk.setChecked(True)
        self.clf_results_chk.setObjectName("clf_results_chk")
        self.gridLayout_17.addWidget(self.clf_results_chk, 1, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem8, 1, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.save_path_label = QtWidgets.QLabel(self.save_res_gbox)
        self.save_path_label.setObjectName("save_path_label")
        self.horizontalLayout.addWidget(self.save_path_label)
        self.save_path_box = QtWidgets.QLineEdit(self.save_res_gbox)
        self.save_path_box.setObjectName("save_path_box")
        self.horizontalLayout.addWidget(self.save_path_box)
        self.gridLayout_17.addLayout(self.horizontalLayout, 0, 0, 1, 5)
        self.save_res_btn = QtWidgets.QPushButton(self.save_res_gbox)
        self.save_res_btn.setObjectName("save_res_btn")
        self.gridLayout_17.addWidget(self.save_res_btn, 1, 0, 1, 1)
        self.log_file_chk = QtWidgets.QCheckBox(self.save_res_gbox)
        self.log_file_chk.setObjectName("log_file_chk")
        self.gridLayout_17.addWidget(self.log_file_chk, 1, 3, 1, 1)
        self.best_mode_chk = QtWidgets.QCheckBox(self.save_res_gbox)
        self.best_mode_chk.setObjectName("best_mode_chk")
        self.gridLayout_17.addWidget(self.best_mode_chk, 1, 2, 1, 1)
        self.gridLayout_5.addWidget(self.save_res_gbox, 1, 1, 1, 2)
        self.gridLayout_3.addWidget(self.classigy_tab_frame, 1, 0, 2, 1)
        self.tabs.addTab(self.classify_tab, "")
        self.visualize_tab = QtWidgets.QWidget()
        self.visualize_tab.setObjectName("visualize_tab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.visualize_tab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.vis_tab_frame = QtWidgets.QFrame(self.visualize_tab)
        self.vis_tab_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vis_tab_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vis_tab_frame.setObjectName("vis_tab_frame")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.vis_tab_frame)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.vis_fig_gbox = QtWidgets.QGroupBox(self.vis_tab_frame)
        self.vis_fig_gbox.setObjectName("vis_fig_gbox")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.vis_fig_gbox)
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem9, 2, 0, 1, 1)
        self.vis_status_msg = QtWidgets.QLabel(self.vis_fig_gbox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vis_status_msg.setFont(font)
        self.vis_status_msg.setTextFormat(QtCore.Qt.AutoText)
        self.vis_status_msg.setObjectName("vis_status_msg")
        self.gridLayout_23.addWidget(self.vis_status_msg, 0, 2, 1, 1)
        self.vis_plot_btn = QtWidgets.QPushButton(self.vis_fig_gbox)
        self.vis_plot_btn.setEnabled(False)
        self.vis_plot_btn.setObjectName("vis_plot_btn")
        self.gridLayout_23.addWidget(self.vis_plot_btn, 0, 0, 1, 1)
        self.vis_status = QtWidgets.QLabel(self.vis_fig_gbox)
        self.vis_status.setObjectName("vis_status")
        self.gridLayout_23.addWidget(self.vis_status, 0, 1, 1, 1)
        self.vis_plot_frame = QtWidgets.QFrame(self.vis_fig_gbox)
        self.vis_plot_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vis_plot_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.vis_plot_frame.setObjectName("vis_plot_frame")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.vis_plot_frame)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.plot_frame_grid = QtWidgets.QGridLayout()
        self.plot_frame_grid.setObjectName("plot_frame_grid")
        self.gridLayout_24.addLayout(self.plot_frame_grid, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.vis_plot_frame, 1, 1, 2, 3)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem10, 0, 3, 1, 1)
        self.gridLayout_18.addWidget(self.vis_fig_gbox, 4, 0, 1, 3)
        self.vis_clf_gbox = QtWidgets.QGroupBox(self.vis_tab_frame)
        self.vis_clf_gbox.setTitle("")
        self.vis_clf_gbox.setObjectName("vis_clf_gbox")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.vis_clf_gbox)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.vis_clf_gbox)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.vis_lin_rbtn = QtWidgets.QRadioButton(self.vis_clf_gbox)
        self.vis_lin_rbtn.setChecked(True)
        self.vis_lin_rbtn.setObjectName("vis_lin_rbtn")
        self.horizontalLayout_4.addWidget(self.vis_lin_rbtn)
        self.vis_non_lin_rbtn = QtWidgets.QRadioButton(self.vis_clf_gbox)
        self.vis_non_lin_rbtn.setObjectName("vis_non_lin_rbtn")
        self.horizontalLayout_4.addWidget(self.vis_non_lin_rbtn)
        self.gridLayout_20.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.vis_clf_label = QtWidgets.QLabel(self.vis_clf_gbox)
        self.vis_clf_label.setObjectName("vis_clf_label")
        self.horizontalLayout_5.addWidget(self.vis_clf_label)
        self.vis_clf_cbox = QtWidgets.QComboBox(self.vis_clf_gbox)
        self.vis_clf_cbox.setObjectName("vis_clf_cbox")
        self.vis_clf_cbox.addItem("")
        self.vis_clf_cbox.addItem("")
        self.horizontalLayout_5.addWidget(self.vis_clf_cbox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.vis_mc_scheme = QtWidgets.QLabel(self.vis_clf_gbox)
        self.vis_mc_scheme.setObjectName("vis_mc_scheme")
        self.horizontalLayout_2.addWidget(self.vis_mc_scheme)
        self.vis_mc_cbox = QtWidgets.QComboBox(self.vis_clf_gbox)
        self.vis_mc_cbox.setEnabled(False)
        self.vis_mc_cbox.setObjectName("vis_mc_cbox")
        self.vis_mc_cbox.addItem("")
        self.vis_mc_cbox.addItem("")
        self.horizontalLayout_2.addWidget(self.vis_mc_cbox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout_20.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.h_params_gbox = QtWidgets.QGroupBox(self.vis_clf_gbox)
        self.h_params_gbox.setObjectName("h_params_gbox")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.h_params_gbox)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vis_C1_label = QtWidgets.QLabel(self.h_params_gbox)
        self.vis_C1_label.setObjectName("vis_C1_label")
        self.horizontalLayout_3.addWidget(self.vis_C1_label)
        self.vis_C1_val = QtWidgets.QSpinBox(self.h_params_gbox)
        self.vis_C1_val.setMinimum(-10)
        self.vis_C1_val.setMaximum(10)
        self.vis_C1_val.setProperty("value", 1)
        self.vis_C1_val.setObjectName("vis_C1_val")
        self.horizontalLayout_3.addWidget(self.vis_C1_val)
        self.vis_C2_label = QtWidgets.QLabel(self.h_params_gbox)
        self.vis_C2_label.setObjectName("vis_C2_label")
        self.horizontalLayout_3.addWidget(self.vis_C2_label)
        self.vis_C2_val = QtWidgets.QSpinBox(self.h_params_gbox)
        self.vis_C2_val.setMinimum(-10)
        self.vis_C2_val.setMaximum(10)
        self.vis_C2_val.setProperty("value", 1)
        self.vis_C2_val.setObjectName("vis_C2_val")
        self.horizontalLayout_3.addWidget(self.vis_C2_val)
        self.vix_u_label = QtWidgets.QLabel(self.h_params_gbox)
        self.vix_u_label.setObjectName("vix_u_label")
        self.horizontalLayout_3.addWidget(self.vix_u_label)
        self.vis_u_value = QtWidgets.QSpinBox(self.h_params_gbox)
        self.vis_u_value.setMinimum(-10)
        self.vis_u_value.setMaximum(10)
        self.vis_u_value.setProperty("value", 1)
        self.vis_u_value.setObjectName("vis_u_value")
        self.horizontalLayout_3.addWidget(self.vis_u_value)
        self.gridLayout_19.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_20.addWidget(self.h_params_gbox, 0, 2, 1, 1)
        self.gridLayout_18.addWidget(self.vis_clf_gbox, 0, 0, 1, 1)
        self.vis_options_gbox = QtWidgets.QGroupBox(self.vis_tab_frame)
        self.vis_options_gbox.setObjectName("vis_options_gbox")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.vis_options_gbox)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.vis_save_gbox = QtWidgets.QGroupBox(self.vis_options_gbox)
        self.vis_save_gbox.setTitle("")
        self.vis_save_gbox.setObjectName("vis_save_gbox")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.vis_save_gbox)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.vis_save_fig_chk = QtWidgets.QCheckBox(self.vis_save_gbox)
        self.vis_save_fig_chk.setObjectName("vis_save_fig_chk")
        self.horizontalLayout_6.addWidget(self.vis_save_fig_chk)
        self.vis_save_label = QtWidgets.QLabel(self.vis_save_gbox)
        self.vis_save_label.setObjectName("vis_save_label")
        self.horizontalLayout_6.addWidget(self.vis_save_label)
        self.vis_save_val = QtWidgets.QLineEdit(self.vis_save_gbox)
        self.vis_save_val.setEnabled(False)
        self.vis_save_val.setObjectName("vis_save_val")
        self.horizontalLayout_6.addWidget(self.vis_save_val)
        self.vis_select_btn = QtWidgets.QPushButton(self.vis_save_gbox)
        self.vis_select_btn.setEnabled(False)
        self.vis_select_btn.setObjectName("vis_select_btn")
        self.horizontalLayout_6.addWidget(self.vis_select_btn)
        self.gridLayout_21.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_22.addWidget(self.vis_save_gbox, 0, 2, 2, 1)
        self.vis_dpi_val = QtWidgets.QSpinBox(self.vis_options_gbox)
        self.vis_dpi_val.setMinimum(8)
        self.vis_dpi_val.setMaximum(2048)
        self.vis_dpi_val.setProperty("value", 128)
        self.vis_dpi_val.setObjectName("vis_dpi_val")
        self.gridLayout_22.addWidget(self.vis_dpi_val, 0, 1, 1, 1)
        self.vis_dpi_label = QtWidgets.QLabel(self.vis_options_gbox)
        self.vis_dpi_label.setObjectName("vis_dpi_label")
        self.gridLayout_22.addWidget(self.vis_dpi_label, 0, 0, 1, 1)
        self.vis_db_chk = QtWidgets.QCheckBox(self.vis_options_gbox)
        self.vis_db_chk.setObjectName("vis_db_chk")
        self.gridLayout_22.addWidget(self.vis_db_chk, 1, 0, 1, 2)
        self.gridLayout_18.addWidget(self.vis_options_gbox, 2, 0, 1, 3)
        self.gridLayout_15.addWidget(self.vis_tab_frame, 0, 0, 1, 1)
        self.tabs.addTab(self.visualize_tab, "")
        self.model_tab = QtWidgets.QWidget()
        self.model_tab.setAutoFillBackground(False)
        self.model_tab.setObjectName("model_tab")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.model_tab)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.model_tab_frame = QtWidgets.QFrame(self.model_tab)
        self.model_tab_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.model_tab_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.model_tab_frame.setObjectName("model_tab_frame")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.model_tab_frame)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.model_test_gbox = QtWidgets.QGroupBox(self.model_tab_frame)
        self.model_test_gbox.setObjectName("model_test_gbox")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.model_test_gbox)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.status_gbox = QtWidgets.QGroupBox(self.model_test_gbox)
        self.status_gbox.setTitle("")
        self.status_gbox.setObjectName("status_gbox")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.status_gbox)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.model_status_label = QtWidgets.QLabel(self.status_gbox)
        self.model_status_label.setObjectName("model_status_label")
        self.horizontalLayout_7.addWidget(self.model_status_label)
        self.model_status_msg = QtWidgets.QLabel(self.status_gbox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.model_status_msg.setFont(font)
        self.model_status_msg.setObjectName("model_status_msg")
        self.horizontalLayout_7.addWidget(self.model_status_msg)
        self.gridLayout_27.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.gridLayout_32.addWidget(self.status_gbox, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.model_eval_btn = QtWidgets.QPushButton(self.model_test_gbox)
        self.model_eval_btn.setEnabled(False)
        self.model_eval_btn.setObjectName("model_eval_btn")
        self.horizontalLayout_10.addWidget(self.model_eval_btn)
        self.model_pred_chk = QtWidgets.QCheckBox(self.model_test_gbox)
        self.model_pred_chk.setEnabled(False)
        self.model_pred_chk.setObjectName("model_pred_chk")
        self.horizontalLayout_10.addWidget(self.model_pred_chk)
        self.gridLayout_32.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.mdoel_acc_label = QtWidgets.QLabel(self.model_test_gbox)
        self.mdoel_acc_label.setObjectName("mdoel_acc_label")
        self.horizontalLayout_9.addWidget(self.mdoel_acc_label)
        self.model_acc_val = QtWidgets.QLabel(self.model_test_gbox)
        self.model_acc_val.setObjectName("model_acc_val")
        self.horizontalLayout_9.addWidget(self.model_acc_val)
        self.gridLayout_32.addLayout(self.horizontalLayout_9, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.model_te_time_label = QtWidgets.QLabel(self.model_test_gbox)
        self.model_te_time_label.setObjectName("model_te_time_label")
        self.horizontalLayout_11.addWidget(self.model_te_time_label)
        self.model_te_time_val = QtWidgets.QLabel(self.model_test_gbox)
        self.model_te_time_val.setObjectName("model_te_time_val")
        self.horizontalLayout_11.addWidget(self.model_te_time_val)
        self.gridLayout_32.addLayout(self.horizontalLayout_11, 3, 0, 1, 1)
        self.gridLayout_26.addWidget(self.model_test_gbox, 2, 1, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_26.addItem(spacerItem11, 3, 0, 1, 1)
        self.model_tab_gbox = QtWidgets.QGroupBox(self.model_tab_frame)
        self.model_tab_gbox.setObjectName("model_tab_gbox")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.model_tab_gbox)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.model_load_btn = QtWidgets.QPushButton(self.model_tab_gbox)
        self.model_load_btn.setEnabled(False)
        self.model_load_btn.setObjectName("model_load_btn")
        self.gridLayout_29.addWidget(self.model_load_btn, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem12, 0, 1, 1, 1)
        self.mdoel_tab_info = QtWidgets.QGroupBox(self.model_tab_gbox)
        self.mdoel_tab_info.setObjectName("mdoel_tab_info")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.mdoel_tab_info)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.model_hyp_gbox = QtWidgets.QGroupBox(self.mdoel_tab_info)
        self.model_hyp_gbox.setObjectName("model_hyp_gbox")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.model_hyp_gbox)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.model_C1_val = QtWidgets.QLabel(self.model_hyp_gbox)
        self.model_C1_val.setObjectName("model_C1_val")
        self.gridLayout_31.addWidget(self.model_C1_val, 0, 1, 1, 1)
        self.model_C1_label = QtWidgets.QLabel(self.model_hyp_gbox)
        self.model_C1_label.setObjectName("model_C1_label")
        self.gridLayout_31.addWidget(self.model_C1_label, 0, 0, 1, 1)
        self.model_C2_label = QtWidgets.QLabel(self.model_hyp_gbox)
        self.model_C2_label.setObjectName("model_C2_label")
        self.gridLayout_31.addWidget(self.model_C2_label, 0, 2, 1, 1)
        self.model_C2_val = QtWidgets.QLabel(self.model_hyp_gbox)
        self.model_C2_val.setObjectName("model_C2_val")
        self.gridLayout_31.addWidget(self.model_C2_val, 0, 3, 1, 1)
        self.model_u_label = QtWidgets.QLabel(self.model_hyp_gbox)
        self.model_u_label.setObjectName("model_u_label")
        self.gridLayout_31.addWidget(self.model_u_label, 0, 4, 1, 1)
        self.model_u_val = QtWidgets.QLabel(self.model_hyp_gbox)
        self.model_u_val.setObjectName("model_u_val")
        self.gridLayout_31.addWidget(self.model_u_val, 0, 5, 1, 1)
        self.gridLayout_30.addWidget(self.model_hyp_gbox, 3, 0, 1, 2)
        self.model_clf_name = QtWidgets.QLabel(self.mdoel_tab_info)
        self.model_clf_name.setObjectName("model_clf_name")
        self.gridLayout_30.addWidget(self.model_clf_name, 0, 1, 1, 1)
        self.model_clf_label = QtWidgets.QLabel(self.mdoel_tab_info)
        self.model_clf_label.setObjectName("model_clf_label")
        self.gridLayout_30.addWidget(self.model_clf_label, 0, 0, 1, 1)
        self.model_ker_name = QtWidgets.QLabel(self.mdoel_tab_info)
        self.model_ker_name.setObjectName("model_ker_name")
        self.gridLayout_30.addWidget(self.model_ker_name, 1, 1, 1, 1)
        self.model_ker_label = QtWidgets.QLabel(self.mdoel_tab_info)
        self.model_ker_label.setObjectName("model_ker_label")
        self.gridLayout_30.addWidget(self.model_ker_label, 1, 0, 1, 1)
        self.model_no_p_label = QtWidgets.QLabel(self.mdoel_tab_info)
        self.model_no_p_label.setObjectName("model_no_p_label")
        self.gridLayout_30.addWidget(self.model_no_p_label, 2, 0, 1, 1)
        self.model_n_p_val = QtWidgets.QLabel(self.mdoel_tab_info)
        self.model_n_p_val.setObjectName("model_n_p_val")
        self.gridLayout_30.addWidget(self.model_n_p_val, 2, 1, 1, 1)
        self.gridLayout_29.addWidget(self.mdoel_tab_info, 1, 0, 1, 2)
        self.gridLayout_26.addWidget(self.model_tab_gbox, 2, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem13, 2, 2, 1, 1)
        self.model_import_gbox = QtWidgets.QGroupBox(self.model_tab_frame)
        self.model_import_gbox.setObjectName("model_import_gbox")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.model_import_gbox)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.model_path = QtWidgets.QLabel(self.model_import_gbox)
        self.model_path.setObjectName("model_path")
        self.horizontalLayout_8.addWidget(self.model_path)
        self.model_path_box = QtWidgets.QLineEdit(self.model_import_gbox)
        self.model_path_box.setObjectName("model_path_box")
        self.horizontalLayout_8.addWidget(self.model_path_box)
        self.model_path_btn = QtWidgets.QPushButton(self.model_import_gbox)
        self.model_path_btn.setObjectName("model_path_btn")
        self.horizontalLayout_8.addWidget(self.model_path_btn)
        self.gridLayout_28.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_26.addWidget(self.model_import_gbox, 1, 0, 1, 3)
        self.gridLayout_25.addWidget(self.model_tab_frame, 0, 0, 1, 1)
        self.tabs.addTab(self.model_tab, "")
        self.gridLayout_4.addWidget(self.tabs, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.main_win)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 990, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.cpu_chk_dev = QtWidgets.QAction(MainWindow)
        self.cpu_chk_dev.setCheckable(True)
        self.cpu_chk_dev.setChecked(True)
        self.cpu_chk_dev.setObjectName("cpu_chk_dev")
        self.gpu_chk_dev = QtWidgets.QAction(MainWindow)
        self.gpu_chk_dev.setCheckable(True)
        self.gpu_chk_dev.setObjectName("gpu_chk_dev")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionView_License = QtWidgets.QAction(MainWindow)
        self.actionView_License.setObjectName("actionView_License")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionView_License)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LIBTwinSVM"))
        self.feature_box.setTitle(_translate("MainWindow", "Features"))
        item = self.feature_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        self.import_box.setTitle(_translate("MainWindow", "Import"))
        self.header_check.setText(_translate("MainWindow", "Header"))
        self.sep_label.setText(_translate("MainWindow", "Separator:"))
        self.sep_char_box.setText(_translate("MainWindow", ","))
        self.path_label.setText(_translate("MainWindow", "Path:"))
        self.open_btn.setText(_translate("MainWindow", "Open"))
        self.info_box.setTitle(_translate("MainWindow", "Info"))
        self.feature_label.setText(_translate("MainWindow", "Features:"))
        self.no_features.setText(_translate("MainWindow", "0"))
        self.class_label.setText(_translate("MainWindow", "Classes:"))
        self.no_classes.setText(_translate("MainWindow", "0"))
        self.samples_label.setText(_translate("MainWindow", "Samples:"))
        self.no_samples.setText(_translate("MainWindow", "0"))
        self.read_box.setTitle(_translate("MainWindow", "Read"))
        self.normalize_box.setText(_translate("MainWindow", "Normalize"))
        self.shuffle_box.setText(_translate("MainWindow", "Shuffle"))
        self.load_btn.setText(_translate("MainWindow", "Load"))
        self.tabs.setTabText(self.tabs.indexOf(self.data_tab), _translate("MainWindow", "Data"))
        self.classifiers_box.setTitle(_translate("MainWindow", "Classifiers"))
        self.STSVM_rbtn.setText(_translate("MainWindow", "Standard TwinSVM"))
        self.LSTSVM_rbtn.setText(_translate("MainWindow", "Least Squares TwinSVM"))
        self.mc_box.setTitle(_translate("MainWindow", "Multi-class scheme"))
        self.ova_rbtn.setText(_translate("MainWindow", "One-vs-All"))
        self.ovo_rbtn.setText(_translate("MainWindow", "One-vs-One"))
        self.eval_box.setTitle(_translate("MainWindow", "Evaluation"))
        self.cv_rbtn.setText(_translate("MainWindow", "Cross-validation"))
        self.tt_split_rbtn.setText(_translate("MainWindow", "Train/Test split"))
        self.folds_label.setText(_translate("MainWindow", "Folds:"))
        self.tt_percent_label.setText(_translate("MainWindow", "Percentage:"))
        self.kernel_box.setTitle(_translate("MainWindow", "Kernel"))
        self.lin_kernel_rbtn.setText(_translate("MainWindow", "Linear"))
        self.rbf_kernel_rbtn.setText(_translate("MainWindow", "RBF"))
        self.rect_kernel_rbtn.setText(_translate("MainWindow", "Rectangular"))
        self.percent_label.setText(_translate("MainWindow", "Percentage:"))
        self.hparam_box.setTitle(_translate("MainWindow", "Hyper-Parameters"))
        self.C2_label.setText(_translate("MainWindow", "C2:"))
        self.c2_to_label.setText(_translate("MainWindow", "to"))
        self.C1_label.setText(_translate("MainWindow", "C1:"))
        self.c1_to_label.setText(_translate("MainWindow", "to"))
        self.u_label.setText(_translate("MainWindow", "<html><head/><body><p>u:</p></body></html>"))
        self.u_to_label.setText(_translate("MainWindow", "to"))
        self.step_label.setText(_translate("MainWindow", "Step:"))
        self.gs_box.setTitle(_translate("MainWindow", "Grid Search"))
        self.elapsed_time.setText(_translate("MainWindow", "00:00:00"))
        self.acc.setText(_translate("MainWindow", "0.0"))
        self.run_btn.setText(_translate("MainWindow", "Run!"))
        self.acc_label.setText(_translate("MainWindow", "Acc:"))
        self.best_acc_label.setText(_translate("MainWindow", "Best Acc:"))
        self.elapsed_t_label.setText(_translate("MainWindow", "Elapsed:"))
        self.best_acc.setText(_translate("MainWindow", "0.0"))
        self.save_res_gbox.setTitle(_translate("MainWindow", "Save"))
        self.clf_results_chk.setText(_translate("MainWindow", "Classification Results"))
        self.save_path_label.setText(_translate("MainWindow", "Path:"))
        self.save_res_btn.setText(_translate("MainWindow", "Select"))
        self.log_file_chk.setText(_translate("MainWindow", "Log File"))
        self.best_mode_chk.setText(_translate("MainWindow", "Best Model"))
        self.tabs.setTabText(self.tabs.indexOf(self.classify_tab), _translate("MainWindow", "Classify"))
        self.vis_fig_gbox.setTitle(_translate("MainWindow", "Figure"))
        self.vis_status_msg.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#000000;\">Load a dataset first!</span></p></body></html>"))
        self.vis_plot_btn.setText(_translate("MainWindow", "Plot"))
        self.vis_status.setText(_translate("MainWindow", "Status:"))
        self.label.setText(_translate("MainWindow", "Kernel:"))
        self.vis_lin_rbtn.setText(_translate("MainWindow", "Linear"))
        self.vis_non_lin_rbtn.setText(_translate("MainWindow", "Non-Linear"))
        self.vis_clf_label.setText(_translate("MainWindow", "Classifier:"))
        self.vis_clf_cbox.setItemText(0, _translate("MainWindow", "Standard TwinSVM"))
        self.vis_clf_cbox.setItemText(1, _translate("MainWindow", "Least Squares TwinSVM"))
        self.vis_mc_scheme.setText(_translate("MainWindow", "Multi-class scheme:"))
        self.vis_mc_cbox.setItemText(0, _translate("MainWindow", "One-vs-All"))
        self.vis_mc_cbox.setItemText(1, _translate("MainWindow", "One-vs-One"))
        self.h_params_gbox.setTitle(_translate("MainWindow", "Hyper-Parameters"))
        self.vis_C1_label.setText(_translate("MainWindow", "C1: "))
        self.vis_C2_label.setText(_translate("MainWindow", "C2:"))
        self.vix_u_label.setText(_translate("MainWindow", "u:"))
        self.vis_options_gbox.setTitle(_translate("MainWindow", "Options"))
        self.vis_save_fig_chk.setText(_translate("MainWindow", "Save Figure"))
        self.vis_save_label.setText(_translate("MainWindow", "Path:"))
        self.vis_select_btn.setText(_translate("MainWindow", "Select"))
        self.vis_dpi_label.setText(_translate("MainWindow", "DPI:"))
        self.vis_db_chk.setText(_translate("MainWindow", "Decision Boundary"))
        self.tabs.setTabText(self.tabs.indexOf(self.visualize_tab), _translate("MainWindow", "Visualize"))
        self.model_test_gbox.setTitle(_translate("MainWindow", "Test Phase"))
        self.model_status_label.setText(_translate("MainWindow", "Status:"))
        self.model_status_msg.setText(_translate("MainWindow", "Load test samples first!"))
        self.model_eval_btn.setText(_translate("MainWindow", "Evaluate"))
        self.model_pred_chk.setText(_translate("MainWindow", "Save Predictions"))
        self.mdoel_acc_label.setText(_translate("MainWindow", "Accuracy:"))
        self.model_acc_val.setText(_translate("MainWindow", "0.0"))
        self.model_te_time_label.setText(_translate("MainWindow", "Test Time:"))
        self.model_te_time_val.setText(_translate("MainWindow", "0"))
        self.model_tab_gbox.setTitle(_translate("MainWindow", "Model"))
        self.model_load_btn.setText(_translate("MainWindow", "Load"))
        self.mdoel_tab_info.setTitle(_translate("MainWindow", "Info"))
        self.model_hyp_gbox.setTitle(_translate("MainWindow", "Hyper-Parameters"))
        self.model_C1_val.setText(_translate("MainWindow", "0.25"))
        self.model_C1_label.setText(_translate("MainWindow", "C1:"))
        self.model_C2_label.setText(_translate("MainWindow", "C2:"))
        self.model_C2_val.setText(_translate("MainWindow", "0.1"))
        self.model_u_label.setText(_translate("MainWindow", "u:"))
        self.model_u_val.setText(_translate("MainWindow", "0.125"))
        self.model_clf_name.setText(_translate("MainWindow", "Standard TwinSVM"))
        self.model_clf_label.setText(_translate("MainWindow", "Classifier:"))
        self.model_ker_name.setText(_translate("MainWindow", "Linear"))
        self.model_ker_label.setText(_translate("MainWindow", "Kernel:"))
        self.model_no_p_label.setText(_translate("MainWindow", "No. Parameters:"))
        self.model_n_p_val.setText(_translate("MainWindow", "1000"))
        self.model_import_gbox.setTitle(_translate("MainWindow", "Import"))
        self.model_path.setText(_translate("MainWindow", "Path:"))
        self.model_path_btn.setText(_translate("MainWindow", "Select"))
        self.tabs.setTabText(self.tabs.indexOf(self.model_tab), _translate("MainWindow", "Model"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.cpu_chk_dev.setText(_translate("MainWindow", "CPU"))
        self.gpu_chk_dev.setText(_translate("MainWindow", "GPU"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionView_License.setText(_translate("MainWindow", "View License "))
        self.actionAbout.setText(_translate("MainWindow", "About"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

